### ISSUE TITLE
fatal error each time

### ISSUE THREAD

**Issue by limikael** [tunapanda/wp-xapi-lrs#4]
According to a report received per email, there is a fatal error on this line:

/home/..../wp-content/plugins/wp-xapi-lrs/ext/minixapi/ext/TinCanPHP/autoload.php on line 40

Don't know what error, awaiting further feedback.

**Comment by MicheleM68** [comment]
The error is received when trying to activate the plugin.

"Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[', expecting ')' in /xxx/xxx/xxx/xxxxxxxx/wp-content/plugins/wp-xapi-lrs/ext/minixapi/ext/TinCanPHP/autoload.php on line 40"

**Comment by limikael** [comment]
Aha... So I think this might have to do with the PHP version. May I ask which version you use?

We are using [this](https://github.com/RusticiSoftware/TinCanPHP) library, and it says that it requires at least PHP version 5.5.

Are you maybe using an older version? If that's the case, there is not much we can do except making sure that the error message is more informative.

**Comment by MicheleM68** [comment]
Our servers are using PHP version 5.5.9. The Wordpress version we are trying to install on is 4.7.2.

**Comment by limikael** [comment]
Hi,

I tried it with some older versions of PHP, and in fact it worked fine with PHP 5.5.9. It worked fine for me with PHP 5.4 as well, but when I tried PHP 5.3 I got the exact same error as you are describing.

Are you sure about the PHP version on your server?

I published a new version (0.0.3) of the plugin here: https://wordpress.org/plugins/wp-xapi-lrs/ where I added a check for the php version. Can you test the new version please and see what error you are getting?

**Comment by limikael** [comment]
@MicheleM68 any update?

**Comment by MicheleM68** [comment]
I apologize. While our servers are running version 5.5.9, the client in question is actually running 5.3.3. It did not occur to me that this particular client had their own server. It is indeed the PHP version that is causing the issue. Thanks for your help!

**Comment by limikael** [comment]
Good to hear! Thanks!
